kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: postgres-db
  annotations:
    helm.sh/resource-policy: keep
data:
  user: {{ include "matrix.psqluser" . | b64enc }}
  password: {{ include "matrix.psqlpass" . | b64enc }}
