name: Continuous Integration - Helm

on:
  pull_request:
    paths:
    - '/**'
    - '.github/workflows/ci-helm-workflow.yml'

permissions:
  contents: read

jobs:
  helm-lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Validate schema
        uses: wiremind/helm-kubeval-action@v1.2.1
        with:
          path: /
          config: /config_repos
          version: 1.23.0

      - uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Cleanup charts directory
        id: cleanup
        run: sudo rm -rf /charts

      - name: Run chart-testing (lint)
        id: lint
        run: ct lint --config=.helm-chart-testing.yaml

      # - name: Create kind cluster
      #   uses: helm/kind-action@v1.2.0

      # - name: Run chart-testing (install)
      #   run: ct install --config=.helm-chart-testing.yaml